### ISSUE TITLE
Sink with "timePartitioningType": "HOUR" not working

### ISSUE THREAD

**Issue by jinoobaek-qz** [confluentinc/kafka-connect-bigquery#120]
With the config below in Kafka 2.6.1 and connector 2.6.1, I'm seeing this work (creates a table with day partitioning and data coming in):

```
{
  "name": "bqSink-<topic-name>",
  "config": {
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "errors.log.enable": true,
    "errors.log.include.messages": true,
    "keySource": "FILE",
    "sanitizeTopics": "true",
    "autoCreateTables": "true",
    "threadPoolSize": "2",
    "bigQueryRetry": "0",
    "bigQueryRetryWait": "10000",
    "consumer.session.timeout.ms": "300000",
    "session.timeout.ms": "210000",
    "offset.flush.timeout.ms": "20000",
    "consumer.request.timeout.ms": "310000",
    "maxWriteSize": "10000",
    "heartbeat.interval.ms": "60100",
    "tableWriteWait": "100000",
    "bufferSize": "10000",
    "batchWriter": "com.wepay.kafka.connect.bigquery.write.batch.SingleBatchWriter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "errors.deadletterqueue.topic.replication.factor": "3",
    "errors.deadletterqueue.context.headers.enable": "true",
    "value.converter.basic.auth.credentials.source": "USER_INFO",
    "schemaRegistryClient.basic.auth.credentials.source": "USER_INFO",
    "basic.auth.credentials.source": "USER_INFO",
    "value.converter.schema.registry.basic.auth.user.info": "<empty>",
    "schemaRegistryClient.basic.auth.user.info": "<empty>",
    "schema.registry.basic.auth.user.info": "<empty>",
    "schemaRegistryLocation": "<empty>",
    "schema.registry.url": "<empty>",
    "value.converter.schema.registry.url": "<empty>",
    "allowSchemaUnionization": "false",
    "allowNewBigQueryFields": "true",
    "allowBigQueryRequiredFieldRelaxation": "true",
    "schemaRetriever": "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever",
    "errors.deadletterqueue.topic.name": "dlq-<topic-name>",
    "topics": "<topic-name>",
    "keyfile": "<some-path>",
    "project": "<gcp-project-id>",
    "tasks.max": "1",
    "defaultDataset": "<dataset>"
  }
}
```

But, when I add  `"timePartitioningType": "HOUR",`, I see that the connector creates a table with hourly partition, but, I do not see any data piping in.

**Comment by C0urante** [comment]
What is the status of the connector via the REST API (`GET /connectors/bqSink-<topic-name>/status`)? Do you see any errors in the logs?

**Comment by jinoobaek-qz** [comment]
I get a 201 response for put request for config and for the status, I get

```{'id': 0, 'state': 'RUNNING', 'worker_id': '<redacted>:8083'}```


I see

```
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=kafka-connect-client-3634cb60-2a96-4569-bd0b-18ba33118797
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:814)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:632)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:613)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.connect.util.KafkaBasedLog.createConsumer(KafkaBasedLog.java:265)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:132)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:268)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:288)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 07 15:03:49 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.lang.Thread.run(Thread.java:834)
```
^^^ seems unrelated

```
Jul 07 15:04:53 3634cb60-2a96-4569-bd0b-18ba33118797 [2021-07-07 15:04:53,393] INFO Attempting to create table `<dataset>`.`<table>` with schema Schema{fields=[Field{name=<field2>, type=RECORD, mode=REQUIRED, description=null, policyTags=null}, Field{name=<field1>, type=RECORD, mode=REQUIRED, description=null, policyTags=null}, Field{name=<field3>, type=INTEGER, mode=REQUIRED, description=The last modified timestamp in milliseconds since epoch for this join, policyTags=null}]} (com.wepay.kafka.connect.bigquery.SchemaManager:224)
```

```
Jul 07 15:10:12 3634cb60-2a96-4569-bd0b-18ba33118797 [2021-07-07 15:10:12,523] INFO [Consumer clientId=connector-consumer-bqSink-<redacted>-20210707_110235-0, groupId=connect-bqSink-<redacted>-20210707_110235] Member connector-consumer-bqSink-<redacted>-20210707_110235-0-80929943-a7e7-407e-95c2-9140cd8befb5 sending LeaveGroup request to coordinator <redacted>:9093 (id: <redacted> rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1016)
```

```
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 [2021-07-07 15:19:29,137] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=<dataset>, tableId=<table>}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:70)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 Exception in thread "pool-4-thread-2" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=<dataset>, tableId=<table>}}
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:145)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.lang.Thread.run(Thread.java:834)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 [2021-07-07 15:19:29,179] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=<dataset>, tableId=<table>}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:70)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 Exception in thread "pool-4-thread-1" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=<dataset>, tableId=<table>}}
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:145)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 07 15:19:29 3634cb60-2a96-4569-bd0b-18ba33118797 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by C0urante** [comment]
I've done some research and it looks like BigQuery doesn't actually support decorator syntax for anything except daily-partitioned tables (https://cloud.google.com/bigquery/streaming-data-into-bigquery#ingestion-time_partitioning).

If you'd like to run the connector against an ingestion time-partitioned table that isn't partitioned by day, then you'll have to set `bigQueryPartitionDecorator` to `false` for now.

We may want to fail the connector fast if `bigQueryPartitionDecorator` is set to `true` and it either detects that it will write to an ingestion time-partitioned table that isn't partitioned by day, or has been configured with a `timePartitioningType` that isn't `DAY` or `NONE`.

**Comment by jinoobaek-qz** [comment]
Thanks for the update. It works now!
