### ISSUE TITLE
in batch mode - if the schema changes, data just disappears with no trace

### ISSUE THREAD

**Issue by ideasculptor** [confluentinc/kafka-connect-bigquery#136]
I added a transformation which writes the metadata timestamp column to a column called timestamp via InsertField transform (also added kafka_offfset, kafka_topic, and kafka_partition).  The next messages were correctly written out to GCS and looking inside a blob showed the new columns.

connect logs showed the blobs being processed and then deleted with no errors.  A check of the table showed no new rows.  The new data just disappeared off into the ether.  No errors, no rows, and the blobs were deleted.

After many minutes passed, I eventually got this (many times) in the logs, but the blobs have already been deleted.  Shouldn't deletes only happen when writes to bigquery actually succeed?  Now that data is just lost.

How does one handle schema evolution when using batch mode if schema changes can't be accommodated?

```
connect            | [2021-09-03 12:35:42,356] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=temporal, tableId=MyDomainEvent}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor)
connect            | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect            | 	at java.base/java.lang.Thread.run(Thread.java:829)
connect            | [2021-09-03 12:35:42,370] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=temporal, tableId=MyDomainEvent}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor)
connect            | Exception in thread "pool-13-thread-104" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to write rows after BQ table creation or schema update within 30 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=temporal, tableId=MyDomainEvent}}
connect            | 	at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:145)
connect            | 	at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
connect            | 	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
connect            | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect            | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect            | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ideasculptor** [comment]
I blew away the entire connect cluster and bq table and started anew.  Creating the connector with the transformation allowed me to use the new columns and finally get table partitioning based on message timestamp, as desired.  But I still doubt that modifying the schema and allowing it to evolve is going to work correctly.  Maybe transformation based evolution isn't supported but schema based evolution is?  I haven't tried it yet.  But that would be unfortunate, if so, though better than no evolution at all.

**Comment by C0urante** [comment]
There should be no difference between schema changes caused by adding, reconfiguring, or removing transformations, and ones caused by upstream (i.e., Kafka data) schema changes. I can't speak to the batch loading behavior but at least as far as the schema changes go, it's important to keep in mind that all updates need to be backwards-compatible based on BigQuery's schema evolution rules. In the case of the `InsertField` SMT, that would mean ensuring that newly-added fields are optional. Other SMTs may not properly update the schemas of records they see at all, or not allow for optional fields to be added instead of required fields. That would be an issue with the SMT, not the connector, though.

I'm also curious about how this is happening with batch loading at all given that the stack trace you provided should only occur when the connector is writing directly to BigQuery and not doing GCS batch loading (which is only necessary with extremely high-throughput datasets to begin with).
