### ISSUE TITLE
Connector crash with IllegalArgumentException

### ISSUE THREAD

**Issue by yetyetanotherusername** [confluentinc/kafka-connect-bigquery#143]
On reading certain topics from our Kafka, I get this exception:

`Exception in thread "pool-50-thread-10" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to write to table
Caused by: java.lang.IllegalArgumentException
	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.cloud.bigquery.BigQueryException: java.lang.IllegalArgumentException
	at com.google.cloud.bigquery.BigQueryException.translateAndThrow(BigQueryException.java:100)
	at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:989)
	at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:106)
	at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
	... 3 more
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:128)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:146)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:146)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:173)
	at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:105)
	at com.google.api.client.http.json.JsonHttpContent.writeTo(JsonHttpContent.java:73)
	at com.google.api.client.http.GZipEncoding.encode(GZipEncoding.java:50)
	at com.google.api.client.http.HttpEncodingStreamingContent.writeTo(HttpEncodingStreamingContent.java:48)
	at com.google.api.client.http.javanet.NetHttpRequest$DefaultOutputWriter.write(NetHttpRequest.java:76)
	at com.google.api.client.http.javanet.NetHttpRequest.writeContentToOutputStream(NetHttpRequest.java:171)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:117)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HtpRequest.execute(HttpRequest.java:1012)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:487)
	at com.google.cloud.bigquery.BigQueryImpl$27.call(BigQueryImpl.java:981)
	at com.google.cloud.bigquery.BigQueryImpl$27.call(BigQueryImpl.java:978)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:977)
	... 6 more`

I have tried setting the logging verbosity to `TRACE` but that didn't change a thing. Is there any way to make it print the message it consumed that caused the exception? I'm having a hard time finding out what the actual issue is.

**Comment by jeonguihyeong** [comment]
It would be bigquery error so find out in bigquery error and convertor pages. what kind of convertor do you use?
avro and json date datetime convrting are different
