### ISSUE TITLE
Error deserializing Avro message for id

### ISSUE THREAD

**Issue by jinoobaek-qz** [confluentinc/kafka-connect-bigquery#151]
Hey team,

I'd appreciate if we can get help with this:

Schema registry version 5.0.4.
Kafka broker version 2.6.1
Connector version 2.6.1
BigQuery Connector version 2.1.4

With the given configuration but with just the topics changed, this works fine. It seems like there might be some issue with the schema registered in the schema registry. It might be because the schema is auto-generated by java streams library vs manually created via an API call.

Any pointers would help. Thanks!

```
{
  "name": "<redacted>",
  "config": {
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "errors.log.enable": true,
    "errors.log.include.messages": true,
    "keySource": "JSON",
    "sanitizeTopics": "true",
    "autoCreateTables": "true",
    "threadPoolSize": "2",
    "bigQueryRetry": "0",
    "bigQueryRetryWait": "10000",
    "consumer.session.timeout.ms": "300000",
    "session.timeout.ms": "210000",
    "offset.flush.timeout.ms": "20000",
    "consumer.request.timeout.ms": "310000",
    "maxWriteSize": "10000",
    "heartbeat.interval.ms": "60100",
    "tableWriteWait": "100000",
    "bufferSize": "10000",
    "batchWriter": "com.wepay.kafka.connect.bigquery.write.batch.SingleBatchWriter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "errors.deadletterqueue.topic.replication.factor": "3",
    "errors.deadletterqueue.context.headers.enable": "true",
    "errors.deadletterqueue.topic.name": "<redacted>",
    "topics": "<redacted>",
    "value.converter.basic.auth.credentials.source": "USER_INFO",
    "schemaRegistryClient.basic.auth.credentials.source": "USER_INFO",
    "basic.auth.credentials.source": "USER_INFO",
    "allowSchemaUnionization": "false",
    "allowNewBigQueryFields": "true",
    "allowBigQueryRequiredFieldRelaxation": "true",
    "schemaRetriever": "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever",
    "value.converter.schema.registry.basic.auth.user.info": "<redacted>",
    "schemaRegistryClient.basic.auth.user.info": "<redacted>",
    "schema.registry.basic.auth.user.info": "<redacted>",
    "schemaRegistryLocation": "<redacted>",
    "schema.registry.url": "<redacted>",
    "value.converter.schema.registry.url": "<redacted>",
    "keyfile": "<redacted>",
    "project": "<redacted>",
    "tasks.max": "2",
    "defaultDataset": "<redacted>"
  }
}
```

```
Sep 15 17:20:58 ff6f4898-4a16-48c1-b909-f6f4841d626d [2021-09-15 17:20:58,526] INFO [Consumer clientId=<redacted>, groupId=<redacted>] Setting offset for partition <redacted> to the committed offset FetchPosition{offset=14921465, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[<redacted>:9093 (id: 1 rack: <redacted>)], epoch=17}} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:814)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d [2021-09-15 17:21:05,152] ERROR Error encountered in task <redacted>. Executing stage 'VALUE_CONVERTER' with class 'io.confluent.connect.avro.AvroConverter', where consumed record is {topic='<redacted>', partition=14, offset=44, timestamp=1621239026045, timestampType=CreateTime}. (org.apache.kafka.connect.runtime.errors.LogReporter:66)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d org.apache.kafka.connect.errors.DataException: <redacted>
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:97)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:498)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:498)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:475)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:229)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.lang.Thread.run(Thread.java:834)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 21
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d Caused by: org.apache.avro.AvroRuntimeException: Can't overwrite property: schema.registry.schema.version
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.avro.JsonProperties.addProp(JsonProperties.java:187)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.avro.Schema.addProp(Schema.java:134)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:165)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:195)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:132)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:84)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:498)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:498)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:475)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:229)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Sep 15 17:21:05 ff6f4898-4a16-48c1-b909-f6f4841d626d 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by C0urante** [comment]
@jinoobaek-qz this stack trace corresponds to the Avro converter, which is a separate project. You may want to check https://github.com/confluentinc/schema-registry (which is the repository that contains the Avro converter) for prior issues similar to yours and, if there are none, create one of your own.
