### ISSUE TITLE
Could not convert to BigQuery schema with a batch of tombstone records error while performing insert without schema

### ISSUE THREAD

**Issue by saumyasuhagiya** [confluentinc/kafka-connect-bigquery#168]
I have an issue in saving to bigquery without providing schema.

Schema is supposed to get generated automatically. Input filetype is json

Kafka connect Config

tasks.max: 1
topics: sample_topic
project: gcp-project-name
defaultDataset: dataset-name
keyfile: key_file_path
group.id: bq-connector
confluent.license: licence_file_path
Error

`[2021-12-01 11:10:16,554] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to unionize schemas of records for the table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=dataset_name, tableId=table_name}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:70)
Exception in thread "pool-9-thread-1" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to unionize schemas of records for the table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=dataset_name, tableId=table_name}}
Caused by: Could not convert to BigQuery schema with a batch of tombstone records.
    at com.wepay.kafka.connect.bigquery.SchemaManager.getTableInfo(SchemaManager.java:283)
    at com.wepay.kafka.connect.bigquery.SchemaManager.createTable(SchemaManager.java:226)
    at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.attemptTableCreate(AdaptiveBigQueryWriter.java:168)
    at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:115)
    at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
    at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Could not convert to BigQuery schema with a batch of tombstone records.
    at com.wepay.kafka.connect.bigquery.SchemaManager.getAndValidateProposedSchema(SchemaManager.java:301)
    at com.wepay.kafka.connect.bigquery.SchemaManager.getTableInfo(SchemaManager.java:280)
    ... 8 more
[2021-12-01 11:10:16,606] ERROR WorkerSinkTask{id=kafka-to-bigquery-sink-connector-0} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:385)
`

I added below configs, but same error

allowBigQueryRequiredFieldRelaxation: true
allBQFieldsNullable: true

**Comment by saumyasuhagiya** [comment]
The question is not understood properly. I am ok to create table beforehand but schema will not be supplied as my input is JSON file.

**Comment by C0urante** [comment]
The error in the original post comes from tombstone records and has nothing to do with schemas.
