### ISSUE TITLE
Convert io.debezium.time.MicroTimestamp to DATETIME

### ISSUE THREAD

**Issue by LarsKlingen** [confluentinc/kafka-connect-bigquery#195]
For legacy reasons I would like to have DATETIME format for columns that come as MicroTimestamp (We use Debezium for postgressql that converts timestamps to MicroTimestamp). The Sink automatically converts to TIMESTAMP format.
I tried creating the table first with type DATETIME for the columns to circumvent this, but then I got the error:

```
Field updated_at has changed type from DATETIME to TIMESTAMP; See logs for more detail
	at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.maybeThrowEncounteredErrors(KCBQThreadPoolExecutor.java:108)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.put(BigQuerySinkTask.java:233)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
	... 10 more
```
Is there a way to save columns as DATETIME on BQ? I also considered using a view to convert to DATETIME, but then we lose the parittioning property on these columns. Thanks!

**Comment by LarsKlingen** [comment]
As described in the link to the other issue this only happens when a new column needs to be added.

**Comment by raphaelauv** [comment]
There is no way with the current connector you need to custom it and rebuild the jar

**Comment by LarsKlingen** [comment]
Thanks for your response @raphaelauv. I was considering using a converter but as far as I saw there is no schema converter that converts any debezium type to BQ Datetime. This one says BQ datetime but actually converts to timestamps:

https://github.com/confluentinc/kafka-connect-bigquery/blob/b798418d554a93b9bd36c059bc468a4079347727/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/logicaltype/DebeziumLogicalConverters.java#L109-L138
