### ISSUE TITLE
ERROR : INVALID_ARGUMENT jobInternalError 

### ISSUE THREAD

**Issue by SebHeuze** [confluentinc/kafka-connect-bigquery#349]
From time to time, we have a jobInternalError 

The jobInternalError is a broad error message, and it can be triggered by various underlying issues.
It can be a temporary network error on our side, or a temporary issue on GCP but it's a problem to have to manually restart the connector each time this happen.

After the connector restart everything is fine and run smoothly again 

If this error is caused by temporary general issues, couldn't be better to consider it as a Retryable error instead of just crashing the connector task ?

The error from GCP : 
```
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "The job encountered an internal error during execution and was unable to complete successfully.",
    "reason" : "jobInternalError"
  } ],
  "message" : "The job encountered an internal error during execution and was unable to complete successfully.",
  "status" : "INVALID_ARGUMENT"
}
```

The stacktrace : 
```
ERROR WorkerSinkTask{id=connector_sink_bigquery-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: A write thread has failed with an unrecoverable error (org.apache.kafka.connect.runtime.WorkerSinkTask:566)
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: A write thread has failed with an unrecoverable error
Caused by: The job encountered an internal error during execution and was unable to complete successfully.
	at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.lambda$maybeThrowEncounteredError$0(KCBQThreadPoolExecutor.java:101)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.maybeThrowEncounteredError(KCBQThreadPoolExecutor.java:100)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.writeSinkRecords(BigQuerySinkTask.java:251)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.put(BigQuerySinkTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.cloud.bigquery.BigQueryException: The job encountered an internal error during execution and was unable to complete successfully.
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:643)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1393)
	at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1388)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1387)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1371)
	at com.google.cloud.bigquery.Job$1.call(Job.java:338)
	at com.google.cloud.bigquery.Job$1.call(Job.java:335)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334)
	at com.google.cloud.bigquery.Job.getQueryResults(Job.java:295)
	at com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1335)
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1283)
	at com.wepay.kafka.connect.bigquery.MergeQueries.mergeFlush(MergeQueries.java:153)
	at com.wepay.kafka.connect.bigquery.MergeQueries.lambda$mergeFlush$1(MergeQueries.java:130)
	... 3 more
```

**Comment by SebHeuze** [comment]
Reply from google assistance : 

The BigQuery Engineering Team shared that your failed job was affected by a spike in traffic which caused system overload in a short period of time. 
With this, they have suggested you rerun the job and advise if the same error still appears at your end.


So we have to change the way the connector handle this error to restart the job

**Comment by b-goyal** [comment]
Apologies for the delay here @SebHeuze.
This sounds like a good suggestion. Please feel free to raise a PR with the change.
