### ISSUE TITLE
Setting kafkaKeyFieldName, when keys are string and topic has no schema, is not working

### ISSUE THREAD

**Issue by jherrmannNetfonds** [confluentinc/kafka-connect-bigquery#352]
Hi, I am using Version: 2.5.1. of the connector and I am using BigQuery as a sink. I want to have the kafka key in the BigQuery target table. But as soon as I set `kafkaKeyFieldName` and `key.converter` in the config I get the following exception. 

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.wepay.kafka.connect.bigquery.exception.ConversionConnectException: Top-level Kafka Connect schema must be of type 'struct'
	at com.wepay.kafka.connect.bigquery.convert.BigQueryRecordConverter.convertRecord(BigQueryRecordConverter.java:90)
	at com.wepay.kafka.connect.bigquery.convert.BigQueryRecordConverter.convertRecord(BigQueryRecordConverter.java:49)
	at com.wepay.kafka.connect.bigquery.utils.SinkRecordConverter.lambda$getRegularRow$2(SinkRecordConverter.java:135)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.wepay.kafka.connect.bigquery.utils.SinkRecordConverter.getRegularRow(SinkRecordConverter.java:134)
	at com.wepay.kafka.connect.bigquery.utils.SinkRecordConverter.getRecordRow(SinkRecordConverter.java:74)
	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter$Builder.addRow(TableWriter.java:196)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.writeSinkRecords(BigQuerySinkTask.java:297)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.put(BigQuerySinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	... 11 more
```

The whole config ist: 
```
{
    "gcsBucketName": "bucket",
    "project": "project",
    "defaultDataset": "dataset",
    "keyfile": "xxxxx",
    "keySource": "JSON",
    "kafkaKeyFieldName": "kafka_key",
    "name": "connector_name",
    "transforms": "transform-1",
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "topics": "source_topic",
    "transforms.transform-1.behavior": "drop_silent",
    "transforms.transform-1.type": "io.aiven.kafka.connect.transforms.TombstoneHandler",
    "value.converter.schemas.enable": "false"
}
```

The keys in the topic are strings and the payload is plain JSON.
The issue seems to originate here https://github.com/confluentinc/kafka-connect-bigquery/blob/add81d88f73f8c4abd48b05956e430570827784c/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverter.java#L87C18-L87C18
I have the feeling `kafkaConnectSchema` can never be null.

Is there a way to have the key in bigquery as a string?

**Comment by b-goyal** [comment]
@jherrmannNetfonds , the connector only accepts Map objects in absence of schema. So storing a key as string is not possible currently.

**Comment by jherrmannNetfonds** [comment]
thx for clarification!
