### ISSUE TITLE
Write errors do not result in the kafka connect task failing

### ISSUE THREAD

**Issue by atrbgithub** [confluentinc/kafka-connect-bigquery#55]
We've noticed that when a BigQuery schema update fails, the kafka-connector and the task itself do not enter a failed state.

For example we see the following error:

```
[2020-11-13 10:16:12,507] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ schema update within 5 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=some_dataset, tableId=some_table_name}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:68)
```
However the status for this task continues to show it as Running. There is no indication of an issue unless you delve into the logs. 

Is this expected?

**Comment by atrbgithub** [comment]
Possibly fixed by this https://github.com/confluentinc/kafka-connect-bigquery/pull/18

**Comment by C0urante** [comment]
Yeah, @atrbgithub which version are you seeing this on? Should be addressed by https://github.com/confluentinc/kafka-connect-bigquery/pull/14 (for which #18 is a follow-up).

**Comment by atrbgithub** [comment]
@C0urante we're using 1.6.1 by the looks of the jar versions. 

Will close this and give the newer versions a try. Hopefully that will solve it. Thank you!

**Comment by atrbgithub** [comment]
@C0urante what's the best way to run the latest version? The confluent docs site still has this as the way to install it via confluent-hub 

```confluent-hub install wepay/kafka-connect-bigquery:latest```

This still gives me 1.6.1. Had a look in maven [here](https://repo1.maven.org/maven2/com/wepay/kcbq/kcbq-connector/) but that only seems to have 1.6.1 as well, plus an alpha version. 

Is there a more recent stable release?

**Comment by C0urante** [comment]
Hmmm... I don't think so. You can try building from source on `master`, but be warned that that will have some backwards-incompatible configuration property changes.

If you'd like to open a backport PR to add the fix from #14 (and hopefully also #18) to the `1.6.x` branch, I'd be happy to review and put out a new release that includes that fix.

**Comment by atrbgithub** [comment]
@C0urante I've raised https://github.com/confluentinc/kafka-connect-bigquery/pull/58. 

Not sure if you chance to review at some point?

**Comment by C0urante** [comment]
@atrbgithub thanks for the PR! I reviewed, approved, and merged it, and have put out a 1.6.6 release that includes the fix and is available on Confluent Hub.

**Comment by atrbgithub** [comment]
@C0urante that is brilliant, thanks for your help! 🙂

**Comment by atrbgithub** [comment]
@C0urante We've merged this however we are still not seeing it fail for the following error:

```
[2020-11-24 09:09:45,984] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: Failed to write rows after BQ table creation or schema update within 5 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=some_dataset, tableId=some_table}} (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:69)
Exception in thread "pool-10-thread-67" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to write rows after BQ table creation or schema update within 5 attempts for: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=some_dataset, tableId=some_table}}
        at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:142)
        at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:119)
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

It looks like this gets thrown here https://github.com/wepay/kafka-connect-bigquery/blob/0483de1d8b7b6e3e053777b665dc1883cdc3fda2/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/row/AdaptiveBigQueryWriter.java#L138-L142

However this is not caught here https://github.com/confluentinc/kafka-connect-bigquery/blob/65eae703f13f0c72d2db514ff82a3bcf16365817/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/write/batch/TableWriter.java#L85

If we caught the error there, would the task be marked as failed?
