### ISSUE TITLE
Failed to deserialize data for topic mycluster.tlp_stress.keyvalue to Avro

### ISSUE THREAD

**Issue by ahmedjami** [confluentinc/kafka-connect-bigquery#57]
Hello,
I'm using Debezium for CDC from Cassandra and polling into a kafka topic.
Converter used:
value.converter=org.apache.kafka.connect.json.JsonConverter

When I run the bq-sink, i get the following error:
```

| [2020-11-23 09:23:26,847] ERROR WorkerSinkTask{id=kcbq-connect1-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
connect_1         | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
connect_1         |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
connect_1         |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:488)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:468)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:324)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:178)
connect_1         |     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:228)
connect_1         |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect_1         |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect_1         |     at java.lang.Thread.run(Thread.java:748)
connect_1         | Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic mycluster.tlp_stress.keyvalue to Avro:

```
It does mean that eh sink doesn't support the JSON format when reading from Kafka ?
Thanks,

**Comment by C0urante** [comment]
@ahmedjami Can you provide the configurations for your Connect worker, your Debezium connector, and your BigQuery connector?

**Comment by ahmedjami** [comment]
@C0urante thanks for your reply
My apologies, I can see from my connect worker that it configured to  use Avro Converter:
```
CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
```
While Debezium is configured to convert values with a JsonConverter... So that is quite normal to have this kind of error...
Once the Jsonconverter has been replaced, the connector works very well 👍
